# Generated by Django 6.1 on 2026-09-02 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(blank=True, default='Togo', max_length=100)),
                ('numero_fiscal', models.CharField(blank=True, help_text='NIF / Registre de commerce', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_entreprises/')),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar (USD)')], default='XOF', max_length=3)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('plan', models.CharField(choices=[('essai', 'Essai gratuit'), ('starter', 'Starter'), ('pro', 'Pro')], default='essai', max_length=20)),
                ('date_fin_essai', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
