# Generated by Django 6.1 on 2026-09-09 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_fin_abonnement',
            field=models.DateField(blank=True, help_text="Date jusqu'à laquelle le plan payant est actif", null=True),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('fedapay_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='entreprises.entreprise')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
