# Generated by Django 6.1 on 2026-09-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(blank=True, help_text='Intitulé du poste (ex: Commercial, Comptable senior...)', max_length=100),
        ),
    ]
