databases:
  - name: factupro-db
    plan: free
    databaseName: factupro
    user: factupro

services:
  - type: web
    name: factupro-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: factupro-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12.0"
